### ISSUE TITLE
[FEAT] External Dynamic Pages > Squeeze Updated > Implement this page

### ISSUE THREAD

**Issue by abanicaisse** [hngprojects/team_kimiko_nextjs_boilerplate#16]
# Description
Develop a modern and engaging Squeeze Page component. This page is designed to capture user emails by offering free templates in exchange, highlighting the benefits of using HNG boilerplate.

# Acceptance Criteria
- The Squeeze Page is implemented according to the provided design.
- The page is fully responsive and displays correctly on all screen sizes.

### Requirements
The page should include the following elements:
- Heading "Why build from Scratch?"
- Subheading explaining the value proposition
- Email capture form with input field and submit button
- High-quality image of a person using a laptop

### Content Details
- Main heading: "Why build from Scratch?"
- Subheading: "Streamline your processes with HNG boilerplate built for efficiency and optimal productivity."
- Form placeholder: "Enter email address"
- Submit button text: "Get Your Free Copy"
-
### Tests
- Ensure all elements render correctly and match the design.
- Verify responsiveness across various device sizes.
- Test form submission functionality and validation.

### Tasks
- [ ] Develop the Squeeze Page component based on the provided design and requirements.
- [ ] Implement responsive layout, ensuring the image and form display properly on all screen sizes.
- [ ] Create the email capture form with proper validation.
- [ ] Integrate the form with backend API for email submission (if applicable).
- [ ] Implement visual feedback for form submission (success/error states).
- [ ]  Optimize the image for web, ensuring fast load times.

# Design Link
[Figma Design - Link](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=1744-15372&t=LlvLFYEEIRSIDIKc-4)

# Image Preview
<img width="906" alt="Screenshot 2024-07-27 at 20 17 34" src="https://github.com/user-attachments/assets/f7fc7c52-f00e-4e49-a7b9-5b59c084a98d">
